### ISSUE TITLE
New PDOnline site

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/gold_coast#3]
New site: https://cogc.cloud.infor.com/ePathway/ePthProd/web/GeneralEnquiry/EnquiryLists.aspx?ModuleCode=LAP

> New PD Online service
> 
> You'll notice some changes to our PD Online service as a result of a new information technology system that we've introduced to support many of the City's functions, including planning and development.
> 
> Applications lodged from 28 June 2018 can be accessed through the new version of PD Online.
> 
> PD Online (applications from 28 June 2018)
> 
> Applications lodged prior to 28 June 2018 can still be accessed through this version.
> 

```
Injecting scraper and running...
Getting 'thisweek' data, changable via MORPH_PERIOD environment
scraper.rb:18:in `clean_whitespace': undefined method `gsub' for nil:NilClass (NoMethodError)
	from scraper.rb:38:in `block in scrape_table'
	from /app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:190:in `block in each'
	from /app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:189:in `upto'
	from /app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:189:in `each'
	from scraper.rb:31:in `scrape_table'
	from scraper.rb:61:in `<main>'
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dmmt)

**Comment by LoveMyData** [comment]
A complete move from ApplicationMaster to ePathway's cloud, a new scraper is needed, not just update an URL.   :-(

and ePathway is not a good friend of scraper because it is very heavily use .Net to track session !!
